# 
# Tasks Dashboard Overview API Request
#

###
# needs month param(1-12)
GET http://localhost/api/dashboard/task/overview
# GET http://localhost/api/dashboard/task/overview?month=11
Accept: application/json
Content-Type: application/json